package br.fosge.engine.runtime.platform.binding.stb.api;

import org.lwjgl.PointerBuffer;
import org.lwjgl.stb.STBVorbisAlloc;
import org.lwjgl.stb.STBVorbisComment;
import org.lwjgl.stb.STBVorbisInfo;

import java.nio.ByteBuffer;
import java.nio.FloatBuffer;
import java.nio.IntBuffer;
import java.nio.ShortBuffer;

public interface STBVorbis {

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS__no_error = 0;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_need_more_data = 1;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_invalid_api_mixing = 2;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_outofmem = 3;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_feature_not_supported = 4;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_too_many_channels = 5;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_file_open_failure = 6;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_seek_without_length = 7;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_unexpected_eof = 10;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_seek_invalid = 11;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_invalid_setup = 20;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_invalid_stream = 21;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_missing_capture_pattern = 30;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_invalid_stream_structure_version = 31;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_continued_packet_flag_invalid = 32;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_incorrect_stream_serial_number = 33;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_invalid_first_page = 34;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_bad_packet_type = 35;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_cant_find_last_page = 36;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_seek_failed = 37;

    /** Error code.  <h5>Enum values:</h5>  <ul> <li>{@link #VORBIS__no_error _no_error}</li> <li>{@link #VORBIS_need_more_data need_more_data}</li> <li>{@link #VORBIS_invalid_api_mixing invalid_api_mixing}</li> <li>{@link #VORBIS_outofmem outofmem}</li> <li>{@link #VORBIS_feature_not_supported feature_not_supported}</li> <li>{@link #VORBIS_too_many_channels too_many_channels}</li> <li>{@link #VORBIS_file_open_failure file_open_failure}</li> <li>{@link #VORBIS_seek_without_length seek_without_length}</li> <li>{@link #VORBIS_unexpected_eof unexpected_eof}</li> <li>{@link #VORBIS_seek_invalid seek_invalid}</li> <li>{@link #VORBIS_invalid_setup invalid_setup}</li> <li>{@link #VORBIS_invalid_stream invalid_stream}</li> <li>{@link #VORBIS_missing_capture_pattern missing_capture_pattern}</li> <li>{@link #VORBIS_invalid_stream_structure_version invalid_stream_structure_version}</li> <li>{@link #VORBIS_continued_packet_flag_invalid continued_packet_flag_invalid}</li> <li>{@link #VORBIS_incorrect_stream_serial_number incorrect_stream_serial_number}</li> <li>{@link #VORBIS_invalid_first_page invalid_first_page}</li> <li>{@link #VORBIS_bad_packet_type bad_packet_type}</li> <li>{@link #VORBIS_cant_find_last_page cant_find_last_page}</li> <li>{@link #VORBIS_seek_failed seek_failed}</li> <li>{@link #VORBIS_ogg_skeleton_not_supported ogg_skeleton_not_supported}</li> </ul>*/
    int VORBIS_ogg_skeleton_not_supported = 38;

    /** Returns general information about the specified file.@param f an ogg vorbis file decoder*/
    STBVorbisInfo stb_vorbis_get_info(long f, STBVorbisInfo __result);

    /** Returns ogg comments.@param f an ogg vorbis file decoder*/
    STBVorbisComment stb_vorbis_get_comment(long f, STBVorbisComment __result);

    /** Returns the last error detected (clears it, too).@param f an ogg vorbis file decoder*/
    int stb_vorbis_get_error(long f);

    /** Closes an ogg vorbis file and free all memory in use@param f an ogg vorbis file decoder*/
    void stb_vorbis_close(long f);

    /** Returns the offset (in samples) from the beginning of the file that will be returned by the next decode, if it is known, or -1 otherwise. After a {@link #stb_vorbis_flush_pushdata flush_pushdata} call, this may take a while before it becomes valid again.  <p>NOT WORKING YET after a seek with PULLDATA API.</p>@param f an ogg vorbis file decoder*/
    int stb_vorbis_get_sample_offset(long f);

    /** Returns the current seek point within the file, or offset from the beginning of the memory buffer. In pushdata mode it returns 0.@param f an ogg vorbis file decoder*/
    int stb_vorbis_get_file_offset(long f);

    /** Creates a vorbis decoder by passing in the initial data block containing the ogg&amp;vorbis headers (you don't need to do parse them, just provide the first N bytes of the file -- you're told if it's not enough, see below)@param datablock the data block containing the ogg vorbis headers@param datablock_memory_consumed_in_bytes returns the amount of data parsed/consumed, in bytes@param error returns the error code@param alloc_buffer an {@link STBVorbisAlloc} struct@return On success, returns an {@code stb_vorbis *}, does not set error, returns the amount of data parsed/consumed on this call in         {@code *datablock_memory_consumed_in_bytes}; On failure, returns {@code NULL} on error and sets {@code *error}, does not change         {@code *datablock_memory_consumed}. If it returns {@code NULL} and {@code *error} is {@link #VORBIS_need_more_data need_more_data}, then the input block was incomplete and you need to pass         in a larger block from the start of the file.*/
    long stb_vorbis_open_pushdata(ByteBuffer datablock, IntBuffer datablock_memory_consumed_in_bytes, IntBuffer error, STBVorbisAlloc alloc_buffer);

    /** Decodes a frame of audio sample data if possible from the passed-in data block.  <p>Note that on resynch, stb_vorbis will rarely consume all of the buffer, instead only {@code datablock_length_in_bytes-3} or less. This is because it wants to avoid missing parts of a page header if they cross a datablock boundary, without writing state-machiney code to record a partial detection.</p>  <p>The number of channels returned are stored in *channels (which can be {@code NULL} -- it is always the same as the number of channels reported by {@link #stb_vorbis_get_info get_info}). {@code *output} will contain an array of {@code float*} buffers, one per channel. In other words, {@code (*output)[0][0]} contains the first sample from the first channel, and {@code (*output)[1][0]} contains the first sample from the second channel.</p>  <p>{@code *output} points into stb_vorbis's internal output buffer storage; these buffers are owned by stb_vorbis and application code should not free them or modify their contents. They are transient and will be overwritten once you ask for more data to get decoded, so be sure to grab any data you need before then.</p>@param f an ogg vorbis file decoder@param datablock the data block containing the audio sample data@param channels place to write number of {@code float *} buffers@param output place to write float ** array of float * buffers@param samples place to write number of output samples@return the number of bytes we used from datablock. Possible cases:                  <ul>         <li>0 bytes used, 0 samples output (need more data)</li>         <li>N bytes used, 0 samples output (resynching the stream, keep going)</li>         <li>N bytes used, M samples output (one frame of data)</li>         </ul>                  <p>Note that after opening a file, you will ALWAYS get one N-bytes,0-sample frame, because Vorbis always "discards" the first frame.</p>*/
    int stb_vorbis_decode_frame_pushdata(long f, ByteBuffer datablock, IntBuffer channels, PointerBuffer output, IntBuffer samples);

    /** Inform stb_vorbis that your next datablock will not be contiguous with previous ones (e.g. you've seeked in the data); future attempts to decode frames will cause stb_vorbis to resynchronize (as noted above), and once it sees a valid Ogg page (typically 4-8KB, as large as 64KB), it will begin decoding the <b>next</b> frame.  <p>If you want to seek using pushdata, you need to seek in your file, then call stb_vorbis_flush_pushdata(), then start calling decoding, then once decoding is returning you data, call {@link #stb_vorbis_get_sample_offset get_sample_offset}, and if you don't like the result, seek your file again and repeat.</p>@param f an ogg vorbis file decoder*/
    void stb_vorbis_flush_pushdata(long f);

    /** Decode an entire file and output the data interleaved into a {@code malloc()ed} buffer stored in {@code *output}. When you're done with it, just {@link org.lwjgl.system.libc.LibCStdlib#free} the pointer returned in {@code *output}.@param filename the file name@param channels returns the number of channels@param sample_rate returns the sample rate@param output returns a pointer to the decoded data@return the number of samples decoded, or -1 if the file could not be opened or was not an ogg vorbis file*/
    int stb_vorbis_decode_filename(ByteBuffer filename, IntBuffer channels, IntBuffer sample_rate, PointerBuffer output);

    /** Decode an entire file and output the data interleaved into a {@code malloc()ed} buffer stored in {@code *output}. When you're done with it, just {@link org.lwjgl.system.libc.LibCStdlib#free} the pointer returned in {@code *output}.@param filename the file name@param channels returns the number of channels@param sample_rate returns the sample rate@param output returns a pointer to the decoded data@return the number of samples decoded, or -1 if the file could not be opened or was not an ogg vorbis file*/
    int stb_vorbis_decode_filename(CharSequence filename, IntBuffer channels, IntBuffer sample_rate, PointerBuffer output);

    /** Decode an entire file and output the data interleaved into a {@code malloc()ed} buffer stored in {@code *output}. When you're done with it, just {@link org.lwjgl.system.libc.LibCStdlib#free} the pointer returned in {@code *output}.@param filename the file name@param channels returns the number of channels@param sample_rate returns the sample rate@return the number of samples decoded, or -1 if the file could not be opened or was not an ogg vorbis file*/
    ShortBuffer stb_vorbis_decode_filename(CharSequence filename, IntBuffer channels, IntBuffer sample_rate);

    /** In-memory version of {@link #stb_vorbis_decode_filename decode_filename}.@param mem the data to decode@param channels returns the number of channels@param sample_rate returns the sample rate@param output returns a pointer to the decoded data*/
    int stb_vorbis_decode_memory(ByteBuffer mem, IntBuffer channels, IntBuffer sample_rate, PointerBuffer output);

    /** In-memory version of {@link #stb_vorbis_decode_filename decode_filename}.@param mem the data to decode@param channels returns the number of channels@param sample_rate returns the sample rate*/
    ShortBuffer stb_vorbis_decode_memory(ByteBuffer mem, IntBuffer channels, IntBuffer sample_rate);

    /** Creates an ogg vorbis decoder from an ogg vorbis stream in memory (note this must be the entire stream!).@param mem the data to decode@param error returns an error code@param alloc_buffer an {@link STBVorbisAlloc} struct@return the ogg vorbis decoder. On failure, returns {@code NULL} and sets {@code *error}.*/
    long stb_vorbis_open_memory(ByteBuffer mem, IntBuffer error, STBVorbisAlloc alloc_buffer);

    /** Creates an ogg vorbis decoder from a file name.@param filename the file name@param error returns an error code@param alloc_buffer an {@link STBVorbisAlloc} struct@return the ogg vorbis decoder. On failure, returns {@code NULL} and sets {@code *error}.*/
    long stb_vorbis_open_filename(ByteBuffer filename, IntBuffer error, STBVorbisAlloc alloc_buffer);

    /** Creates an ogg vorbis decoder from a file name.@param filename the file name@param error returns an error code@param alloc_buffer an {@link STBVorbisAlloc} struct@return the ogg vorbis decoder. On failure, returns {@code NULL} and sets {@code *error}.*/
    long stb_vorbis_open_filename(CharSequence filename, IntBuffer error, STBVorbisAlloc alloc_buffer);

    /** Seeks in the Vorbis file to (approximately) {@code sample_number}. After calling seek_frame(), the next call to {@code get_frame_*()} will include the specified sample.@param f an ogg vorbis file decoder@param sample_number the sample index*/
    boolean stb_vorbis_seek_frame(long f, int sample_number);

    /** Seeks in the Vorbis file to (approximately) {@code sample_number}. After calling stb_vorbis_seek(), the next call to {@code stb_vorbis_get_samples_*} will start with the specified sample.@param f an ogg vorbis file decoder@param sample_number the sample index*/
    boolean stb_vorbis_seek(long f, int sample_number);

    /** This function is equivalent to {@link #stb_vorbis_seek seek}(f,0).@param f an ogg vorbis file decoder*/
    boolean stb_vorbis_seek_start(long f);

    /** Returns the total length of the vorbis stream, in samples.@param f an ogg vorbis file decoder*/
    int stb_vorbis_stream_length_in_samples(long f);

    /** Returns the total length of the vorbis stream, in samples.@param f an ogg vorbis file decoder*/
    float stb_vorbis_stream_length_in_seconds(long f);

    /** Decodes the next frame and return the number of samples.  <p>You generally should not intermix calls to {@code stb_vorbis_get_frame_*()} and {@code stb_vorbis_get_samples_*()}, since the latter calls the former.</p>@param f an ogg vorbis file decoder@param channels returns the number of channels. Can be {@code NULL} -- it is always the same as the number of channels reported by {@link #stb_vorbis_get_info get_info}.@param output returns a pointer to an array of float* buffers, one per channel. These outputs will be overwritten on the next call to                 {@code stb_vorbis_get_frame_*}.@return the number of samples per channel*/
    int stb_vorbis_get_frame_float(long f, IntBuffer channels, PointerBuffer output);

    /** Decodes the next frame and returns the number of <b>samples</b> per channel. Note that for interleaved data, you pass in the number of shorts (the size of your array), but the return value is the number of samples per channel, not the total number of samples.  <p>The data is coerced to the number of channels you request according to the channel coercion rules (see below). You must pass in the size of your buffer(s) so that stb_vorbis will not overwrite the end of the buffer. The maximum buffer size needed can be gotten from {@link #stb_vorbis_get_info get_info}; however, the Vorbis I specification implies an absolute maximum of 4096 samples per channel.</p>  <h3>Channel coercion rules</h3>  <p>Let M be the number of channels requested, and N the number of channels present, and Cn be the nth channel; let stereo L be the sum of all L and center channels, and stereo R be the sum of all R and center channels (channel assignment from the vorbis spec).</p>  <pre><code> M    N      output 1    _1      sum(Ck) for all _1 2    *      stereo L, stereo R _1    l      _1 &gt; l, the first l channels, then 0s _1    l      _1 &le; l, the first _1 channels</code></pre>  <p>Note that this is not <b>good</b> surround etc. mixing at all! It's just so you get something useful.</p>@param f an ogg vorbis file decoder@param buffer the output buffer, an array of pointers with length {@code num_c}, each pointing to a short array with length {@code num_samples}@param num_samples the number of samples@return the number of samples per channel*/
    int stb_vorbis_get_frame_short(long f, PointerBuffer buffer, int num_samples);

    /** Interleaved version of {@link #stb_vorbis_get_frame_short get_frame_short}.  <p>Note that for interleaved data, you pass in the number of shorts (the size of your array), but the return value is the number of samples per channel, not the total number of samples.</p>@param f an ogg vorbis file decoder@param num_c the number of channels@param buffer the output buffer@return the number of samples per channel*/
    int stb_vorbis_get_frame_short_interleaved(long f, int num_c, ShortBuffer buffer);

    /** Gets {@code num_samples} samples, not necessarily on a frame boundary -- this requires buffering so you have to supply the buffers. DOES NOT APPLY THE COERCION RULES.@param f an ogg vorbis file decoder@param buffer the output buffer, an array of pointers with length {@code channels}, each pointing to a float array with length {@code num_samples}@param num_samples the number of samples to decode@return the number of samples stored per channel; it may be less than requested at the end of the file. If there are no more samples in the file, returns 0.*/
    int stb_vorbis_get_samples_float(long f, PointerBuffer buffer, int num_samples);

    /** Interleaved version of {@link #stb_vorbis_get_samples_float get_samples_float}.@param f an ogg vorbis file decoder@param channels the number of channels@param buffer the output buffer@return the number of samples stored per channel; it may be less than requested at the end of the file. If there are no more samples in the file, returns 0.*/
    int stb_vorbis_get_samples_float_interleaved(long f, int channels, FloatBuffer buffer);

    /** Gets {@code num_samples} samples, not necessarily on a frame boundary -- this requires buffering so you have to supply the buffers. Applies the coercion rules above to produce {@code channels} channels.@param f an ogg vorbis file decoder@param buffer the output buffer, an array of pointers with length {@code channels}, each pointing to a short array with length {@code num_samples}@param num_samples the number of samples@return the number of samples stored per channel; it may be less than requested at the end of the file. If there are no more samples in the file, returns 0.*/
    int stb_vorbis_get_samples_short(long f, PointerBuffer buffer, int num_samples);

    /** Interleaved version of {@link #stb_vorbis_get_samples_short get_samples_short}.@param f an ogg vorbis file decoder@param channels the number of channels@param buffer the output buffer@return the number of samples stored per channel; it may be less than requested at the end of the file. If there are no more samples in the file, returns 0.*/
    int stb_vorbis_get_samples_short_interleaved(long f, int channels, ShortBuffer buffer);

    /** Array version of: {@link #stb_vorbis_open_pushdata open_pushdata}*/
    long stb_vorbis_open_pushdata(ByteBuffer datablock, int[] datablock_memory_consumed_in_bytes, int[] error, STBVorbisAlloc alloc_buffer);

    /** Array version of: {@link #stb_vorbis_decode_frame_pushdata decode_frame_pushdata}*/
    int stb_vorbis_decode_frame_pushdata(long f, ByteBuffer datablock, int[] channels, PointerBuffer output, int[] samples);

    /** Array version of: {@link #stb_vorbis_decode_filename decode_filename}*/
    int stb_vorbis_decode_filename(ByteBuffer filename, int[] channels, int[] sample_rate, PointerBuffer output);

    /** Array version of: {@link #stb_vorbis_decode_filename decode_filename}*/
    int stb_vorbis_decode_filename(CharSequence filename, int[] channels, int[] sample_rate, PointerBuffer output);

    /** Array version of: {@link #stb_vorbis_decode_memory decode_memory}*/
    int stb_vorbis_decode_memory(ByteBuffer mem, int[] channels, int[] sample_rate, PointerBuffer output);

    /** Array version of: {@link #stb_vorbis_open_memory open_memory}*/
    long stb_vorbis_open_memory(ByteBuffer mem, int[] error, STBVorbisAlloc alloc_buffer);

    /** Array version of: {@link #stb_vorbis_open_filename open_filename}*/
    long stb_vorbis_open_filename(ByteBuffer filename, int[] error, STBVorbisAlloc alloc_buffer);

    /** Array version of: {@link #stb_vorbis_open_filename open_filename}*/
    long stb_vorbis_open_filename(CharSequence filename, int[] error, STBVorbisAlloc alloc_buffer);

    /** Array version of: {@link #stb_vorbis_get_frame_float get_frame_float}*/
    int stb_vorbis_get_frame_float(long f, int[] channels, PointerBuffer output);

    /** Array version of: {@link #stb_vorbis_get_frame_short_interleaved get_frame_short_interleaved}*/
    int stb_vorbis_get_frame_short_interleaved(long f, int num_c, short[] buffer);

    /** Array version of: {@link #stb_vorbis_get_samples_float_interleaved get_samples_float_interleaved}*/
    int stb_vorbis_get_samples_float_interleaved(long f, int channels, float[] buffer);

    /** Array version of: {@link #stb_vorbis_get_samples_short_interleaved get_samples_short_interleaved}*/
    int stb_vorbis_get_samples_short_interleaved(long f, int channels, short[] buffer);

}
