---
fosge:
  engine:
    debug: true
    trace: false
    graphics:
      vsync: false
      wireframe: false
    renderer:
      modelMatrix: "un_model"
      viewProjectionMatrix: "un_viewProjection"
  application:
    version:
      major: 0
      minor: 1
      rev: 0
    window:
      title: "Pong"
      resolution: "qHD"
    firstScene: "default"
    scenes:
    - name: "default"
      clearColor: ".25, .33, .18"
      depth:
        enabled: "true"
        function: "LEQUAL"
      blend:
        enabled: "true"
        equation: "FUNC_ADD"
        function:
          source: "SRC_ALPHA"
          target: "ONE_MINUS_SRC_ALPHA"
      camera:
        depth: "-1.0, 1.0"
        rectangle: "-21.0, 21.0, -21.0, 21.0"
      actors:
      - name: "environment"
        identity: "01JJPF8ZPC6ZZ7ZJVC9VVTYHS2"
        components:
        - type: "TRANSFORM_COMPONENT"
          properties:
          - name: "position"
            value: "0, 0, -1"
          - name: "rotation"
            value: "0, 0, 0"
          - name: "scale"
            value: "42, 42, 0"
        - type: "MESH_COMPONENT"
          properties:
          - name: "shader"
            value: "shader/default.glsl"
          - name: "texture.0.asset"
            value: "texture/background.jpg"
          - name: "texture.0.dataType"
            value: "UBYTE"
          - name: "texture.0.storageFormat"
            value: "RGBA8"
          - name: "texture.0.format"
            value: "RGB"
          - name: "texture.0.mips"
            value: "1"
          - name: "geometry.primitive"
            value: "quadrilateral"
        - type: "AUDIO_SOURCE_COMPONENT"
          properties:
          - name: "path"
            value: "audio/music/overworld.ogg"
          - name: "loop"
            value: "true"
          - name: "gain"
            value: "0.3"
        - type: "BEHAVIOUR_COMPONENT"
          properties:
          - name: "target"
            value: "br.fosge.sandbox.pong.EnvironmentController"
      - name: "player"
        identity: "01JKB8JWHSGKBJHMSFSE4Z19EX"
        components:
        - type: "RIGID_BODY_COMPONENT"
        - type: "TRANSFORM_COMPONENT"
          properties:
          - name: "position"
            value: "0, -0.95, 0"
          - name: "rotation"
            value: "0, 0, 0"
          - name: "scale"
            value: "4.5, 1, 0"
        - type: "MESH_COMPONENT"
          properties:
          - name: "shader"
            value: "shader/default.glsl"
          - name: "texture.0.asset"
            value: "texture/paddle.png"
          - name: "texture.0.dataType"
            value: "UBYTE"
          - name: "texture.0.storageFormat"
            value: "RGBA8"
          - name: "texture.0.format"
            value: "RGBA"
          - name: "texture.0.mips"
            value: "1"
          - name: "geometry.primitive"
            value: "quadrilateral"
        - type: "BEHAVIOUR_COMPONENT"
          properties:
          - name: "target"
            value: "br.fosge.sandbox.pong.PlayerController"
          - name: "target.speed"
            value: "1.2"
      - name: "ball"
        identity: "01JKB8JWJWYKTSPXG9AT6V6ZDV"
        components:
        - type: "RIGID_BODY_COMPONENT"
        - type: "TRANSFORM_COMPONENT"
          properties:
          - name: "position"
            value: "-0.2, 0, 0"
          - name: "rotation"
            value: "0, 0, 0"
          - name: "scale"
            value: "2, 02, 0"
        - type: "MESH_COMPONENT"
          properties:
          - name: "shader"
            value: "shader/default.glsl"
          - name: "texture.0.asset"
            value: "texture/awesomeface.png"
          - name: "texture.0.verticalFlip"
            value: "true"
          - name: "texture.0.dataType"
            value: "UBYTE"
          - name: "texture.0.storageFormat"
            value: "RGBA8"
          - name: "texture.0.format"
            value: "RGBA"
          - name: "texture.0.mips"
            value: "1"
          - name: "geometry.primitive"
            value: "quadrilateral"
        - type: "BEHAVIOUR_COMPONENT"
          properties:
          - name: "target"
            value: "br.fosge.sandbox.pong.BallController"
          - name: "target.speed"
            value: "1.2"
