---
fosge:
  engine:
    debug: false
    trace: false
    graphics:
      vsync: false
      wireframe: false
    renderer:
      modelMatrix: "un_model"
      viewProjectionMatrix: "un_viewProjection"
  application:
    version:
      major: 0
      minor: 1
      rev: 0
    window:
      title: "Pong"
      resolution: "qHD"
    firstScene: "default"
    scenes:
    - name: "default"
      clearColor: ".25, .33, .18"
      depth:
        enabled: "true"
        function: "LEQUAL"
      blend:
        enabled: "true"
        equation: "FUNC_ADD"
        function:
          source: "SRC_ALPHA"
          target: "ONE_MINUS_SRC_ALPHA"
      camera:
        properties:
        - name: "depth"
          value: "-1.0, 1.0"
        - name: "rectangle"
          value: "-21.0, 21.0, -21.0, 21.0"
      actors:
      - name: "environment"
        identity: "01JJPF8ZPC6ZZ7ZJVC9VVTYHS2"
        components:
          - type: "MESH_COMPONENT"
            properties:
              - name: "shader"
                value: "shader/default.glsl"
              - name: "texture.0.asset"
                value: "texture/background.jpg"
              - name: "texture.0.dataType"
                value: "UBYTE"
              - name: "texture.0.storageFormat"
                value: "RGBA8"
              - name: "texture.0.format"
                value: "RGB"
              - name: "texture.0.mips"
                value: "1"
              - name: "geometry.primitive"
                value: "quadrilateral"
