---
fosge:
  engine:
    debug: true
    trace: true
    graphics:
      vsync: false
    renderer:
      modelMatrix: "un_model"
      viewProjectionMatrix: "un_viewProjection"
  application:
    version:
      major: 0
      minor: 1
      rev: 0
    window:
      title: "Pong"
      resolution: "FHD"
    firstScene: "default"
    scenes:
    - name: "default"
      clearColor: ".25, .33, .18"
      camera:
        depth: "-1.0, 1.0"
        rectangle: "-21.0, 21.0, -21.0, 21.0"
      actors:
      - name: "environment"
        identity: "01JJPF8ZPC6ZZ7ZJVC9VVTYHS2"
        components:
        - type: "TRANSFORM_COMPONENT"
          properties:
          - name: "position"
            value: "0, 0, 0"
          - name: "rotation"
            value: "0, 0, 0"
          - name: "scale"
            value: "0, 0, 0"
        - type: "AUDIO_SOURCE_COMPONENT"
          properties:
          - name: "path"
            value: "audio/music/overworld.ogg"
          - name: "loop"
            value: "true"
          - name: "gain"
            value: "0.3"
        - type: "BEHAVIOUR_COMPONENT"
          properties:
          - name: "target"
            value: "br.fosge.sandbox.pong.EnvironmentController"
      - name: "player"
        identity: "01JJPMGHGR5T5C3KBVGP2TZWC0"
        components:
        - type: "TRANSFORM_COMPONENT"
          properties:
          - name: "position"
            value: "0, 0, 0"
          - name: "rotation"
            value: "0, 0, 0"
          - name: "scale"
            value: "1, 1, 1"
        - type: "MESH_COMPONENT"
          properties:
          - name: "shader"
            value: "shader/default.glsl"
          - name: "texture.0.asset"
            value: "texture/container.jpg"
          - name: "geometry.primitive"
            value: "quadrilateral"
        - type: "BEHAVIOUR_COMPONENT"
          properties:
          - name: "target"
            value: "br.fosge.sandbox.pong.PlayerController"
          - name: "target.speed"
            value: "2.2"
